tpa:
    resource: "@TpaBundle/Controller/"
    type:     annotation
    prefix:   /

tpa:
    resource: "@tpaBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"